Repository justin-cotarla/CaptionThis, pull requests merged in 2018-02, with the labels that each got.

#56 [#22] Created PUT endpoint for moments creation
  backend/app/routes/moments.js
  backend/package.json
Labels: task

#64 [#63] Fixed the aws-sdk module import in Moments.js
  backend/app/routes/moments.js
Labels: bug, fix

#66 [#37] implement registration route
  backend/app/routes/auth/register.js
  backend/app/routes/index.js
  backend/app/utility/AuthUtil.js
Labels: task

#68 [#65] Fix query to add created moment to database
  backend/app/routes/moments.js
Labels: fix

#77 [#36] implement login route
  backend/app/routes/auth/login.js
  backend/app/routes/index.js
Labels: task

#115 [#114] fix increment bug in caption table
  database/schema.mwb
  database/schema.mwb.bak
Labels: fix

#88 [#86] Create POST endpoints for caption voting
  backend/app/routes/captions.js
  backend/app/routes/moments.js
  frontend/src/pages/MomentCreationPage.js
Labels: task

#122 [#121] Change momentId to take value passed in request.
  backend/app/routes/captions.js
Labels: refactor

#128 [#126] Updates the db query to include the number of votes for each caption
  backend/app/routes/captions.js
Labels: bug, feature

#131 [#120] Add endpoint functionality to update caption when it gets acce…
  backend/app/routes/captions.js
Labels: task

#145 Pressing enter now submits the caption
  frontend/src/components/CaptionCreatorForm.js
  frontend/src/components/CaptionList.js
  frontend/src/styles/CaptionCreatorForm.css
  frontend/src/styles/CaptionList.css
Labels: enhancement
