Repository justin-cotarla/CaptionThis, pull requests merged in 2018-03, with the labels that each got.

#169 Fix caption submission request payload
  frontend/src/components/CaptionCreatorForm.js
Labels: bug

#178 [#177] add test for /api/auth/tokens endpoint
  backend/app/routes/auth/tokens/postTokens.test.js
Labels: P2, task

#187 Working profile page
  backend/app/routes/moments/getMoments.js
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/pages/LandingPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/styles/PageHeader.css
  frontend/src/styles/ProfilePage.css
  frontend/src/styles/ScrollerComponents.css
Labels: feature

#188 [#182] Created test for getMoment
  backend/app/routes/moments/getMoment.js
  backend/app/routes/moments/getMoment.test.js
Labels: task

#190 Changed landing page style
  frontend/src/components/Moment.js
  frontend/src/components/ScrollerComponents.js
  frontend/src/pages/LandingPage.js
  frontend/src/styles/LandingPage.css
  frontend/src/styles/Moment.css
  frontend/src/styles/PageHeader.css
  frontend/src/styles/ScrollerComponents.css
  server/static/logo.png
  server/static/logo1.png
  server/static/polaroid_texture.png
  server/static/uparrow.png
Labels: feature

#213 Add username to GET moment response
  backend/app/routes/moments/getMoment.js
  backend/app/routes/moments/getMoment.test.js
  frontend/src/components/Moment.js
  frontend/src/pages/MomentViewPage.js
Labels: fix

#214 Link usernames to profile pages
  frontend/src/App.css
  frontend/src/components/Caption.js
  frontend/src/components/CaptionList.js
  frontend/src/components/Moment.js
  frontend/src/components/MomentsList.js
  frontend/src/pages/LandingPage.js
  frontend/src/pages/MomentViewPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/styles/Moment.css
  frontend/src/styles/PageHeader.css
  frontend/src/styles/ScrollerComponents.css
Labels: feature, refactor

#216 Fixes the fault in getCaptions
  backend/app/routes/captions/getCaptions.js
Labels: fix

#243 Navbar refactor
  frontend/src/components/NavBar.js
  frontend/src/pages/ProfilePage.js
  frontend/src/styles/NavBar.css
  frontend/src/styles/ProfilePage.css
Labels: enhancement

#244 Error graphic refactor
  frontend/src/components/ErrorGraphic.js
  frontend/src/pages/MomentViewPage.js
  frontend/src/styles/ErrorGraphic.css
  frontend/src/styles/NavBar.css
Labels: refactor

#252 Accepting captions fix
  frontend/src/pages/MomentViewPage.js
Labels: fix

#248 [#89.4] Refactor response codes in captions endpoints
  backend/app/routes/captions/deleteCaptions.js
  backend/app/routes/captions/deleteCaptions.test.js
  backend/app/routes/captions/getCaptions.js
  backend/app/routes/captions/postCaptions.js
  backend/app/routes/captions/postCaptions.test.js
  backend/app/routes/captions/putCaptions.js
  backend/app/routes/captions/putCaptions.test.js
  backend/app/utility/ResponseCodes.js
Labels: refactor

#253 [#239] Refactor response codes for users endpoints and corresponding …
  backend/app/routes/users/getUser.js
  backend/app/routes/users/getUser.test.js
Labels: refactor

#249 100% coverage for putMoments.js
  backend/app/routes/moments/putMoments.js
  backend/app/routes/moments/putMoments.test.js
Labels: task

#257 Sticky navbar
  frontend/src/components/NavBar.js
  frontend/src/styles/NavBar.css
Labels: feature

#258 Create Edit Captions Endpoint
  backend/app/routes/captions/postCaptions.js
  backend/app/routes/captions/postCaptions.test.js
Labels: task

#264 As a programmer, I want to test my code so that I can ensure it is co…
  frontend/src/components/Acceptor.test.js
  frontend/src/components/AuthModal.test.js
  frontend/src/components/AuthRoute.test.js
  frontend/src/components/Caption.test.js
  frontend/src/components/CaptionCreatorForm.test.js
  frontend/src/components/CaptionList.test.js
  frontend/src/components/CaptionVotes.test.js
  frontend/src/components/ErrorGraphic.test.js
  frontend/src/components/Header.test.js
  frontend/src/components/Loading.test.js
  frontend/src/components/LoadingDots.test.js
  frontend/src/components/Moment.test.js
  frontend/src/components/MomentsList.test.js
  frontend/src/components/NavBar.test.js
  frontend/src/components/ScrollerComponents.test.js
  frontend/src/index.test.js
  frontend/src/pages/LandingPage.test.js
  frontend/src/pages/LoginPage.test.js
  frontend/src/pages/MomentCreationPage.test.js
  frontend/src/pages/MomentViewPage.test.js
  frontend/src/pages/ProfilePage.test.js
  frontend/src/pages/RegistrationPage.test.js
  frontend/src/util/AuthUtil.test.js
Labels: task

#281 [#172.3] Minor fix to ensure description shows up on moment viewing page
  backend/app/routes/moments/getMoment.js
  backend/app/routes/moments/getMoment.test.js
Labels: bug

#286 100% coverage for getMoments
  backend/app/routes/moments/getMoments.js
  backend/app/routes/moments/getMoments.test.js
Labels: task

#297 Caption Highlighting
  frontend/package.json
  frontend/src/components/Caption.js
  frontend/src/components/CaptionList.js
  frontend/src/pages/MomentViewPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/styles/Caption.css
  frontend/src/styles/ErrorGraphic.css
  frontend/src/styles/NavBar.css
Labels: feature

#317 Vote-ticker identified by class name
  frontend/src/components/Caption.js
  frontend/src/components/CaptionVotes.js
  frontend/src/styles/CaptionVotes.css
Labels: fix

#306 Adds filtering to caption list
  frontend/src/components/Caption.js
  frontend/src/components/CaptionFilter.js
  frontend/src/components/CaptionList.js
  frontend/src/pages/MomentViewPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/styles/CaptionFilter.css
  frontend/src/styles/CaptionList.css
  frontend/src/styles/ProfilePage.css
  frontend/src/util/apiUtil.js
Labels: feature

#323 [#322] This commit fixes the reload
  frontend/src/components/CaptionList.js
Labels: fix

#324 Fix/caption submit (for real)
  frontend/src/components/CaptionList.js
Labels: fix

#325 Change date to a 'time-ago' format
  frontend/package.json
  frontend/src/components/Caption.js
  frontend/src/components/CaptionCreatorForm.js
  frontend/src/components/CaptionList.js
  frontend/src/components/Moment.js
  frontend/src/pages/MomentViewPage.js
  frontend/src/util/dateUtil.js
Labels: feature

#328 [#327] This commit fixes the date on the profile page captions
  frontend/src/components/Caption.js
  frontend/src/util/dateUtil.js
Labels: fix

#333 [#331] This commit changes the website title
  frontend/public/index.html
  frontend/public/manifest.json
Labels: enhancement

#335 Fix missing react root
  frontend/public/index.html
Labels: bug

#342 Captions are editable on frontend
  frontend/src/components/Caption.js
  frontend/src/components/CaptionList.js
  frontend/src/components/Moment.js
  frontend/src/components/MomentList.js
  frontend/src/pages/LandingPage.js
  frontend/src/pages/MomentViewPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/styles/Caption.css
  frontend/src/styles/CaptionEditor.css
  frontend/src/styles/CaptionVotes.css
  frontend/src/util/apiUtil.js
Labels: feature

#348 Rename apiUtil and dateUtil
  frontend/src/util/ApiUtil.js
  frontend/src/util/DateUtil.js
Labels: P0, fix
